name: CI/CD Pipeline

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azure-ci-cd.yml'

  # Allow manual trigger 
  workflow_dispatch:
jobs:
  build:
    name: Build / Push to ACR
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: flask_test_app
      
    steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3

    - name: "Log in to Azure"
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: "Docker login"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: "Build Dockerfile"
      run: docker build -t ${{secrets.ACR_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{github.sha}} .


      
    - name: Push Docker Image to ACR
      run: docker push ${{secrets.ACR_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{github.sha}}



  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    env:
      CONTAINER_NAME: flask_test_app
      IMAGE_NAME: flask_test_app
   
  
    steps:

    - name: "Checkout Repository"
      uses: actions/checkout@v3
      
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
  
    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
        image: ${{ secrets.ACR_CONTAINER_REGISTRY }}/flask_test_app:${{ github.sha }}
        registry-login-server: ${{ secrets.ACR_CONTAINER_REGISTRY }}
        registry-username: ${{ secrets.ACR_USERNAME }}
        registry-password: ${{ secrets.ACR_PASSWORD }}
        name: aci-sampleapp
        location: 'west us'
